### ISSUE TITLE
Lookup tool incompatible with VS Code 1.57

### ISSUE THREAD

**Issue by nathangibson** [eeditiones/tei-publisher-vscode#7]
Our team _**loves**_ this extension, it makes our lives (i.e. personography tagging) so much easier! 

However, after updating to VS Code 1.57, the lookup function stopped working. Queries that are otherwise found in the lookup (e.g. "Johannes") report "Found 0 items". Also, the search icon has changed to a plain box (as though the icon resource can no longer be loaded?). 

Could this be related to the new "Workspace trust" features introduced in 1.57? I have "trusted" the workspace, so as far as I know the extensions should be enabled. Even if I explicitly add tei-publisher-vscode as a trusted extension, it doesn't help.  

Workaround: Turn off auto-update and install [v1.56](https://code.visualstudio.com/updates/v1_56). Then the extension works. 

Have tried 1.1.0 and at least one earlier version on Mac 10.14.6.

Happy to provide debugging info if you let me know how.

<img width="275" alt="Screen Shot 2021-06-21 at 12 40 24 PM" src="https://user-images.githubusercontent.com/3083452/122749933-34535e80-d28e-11eb-830d-df423cbc2cc0.png">

FYI @wsalesky

**Comment by wolfgangmm** [comment]
Thanks for reporting. It indeed seems to be a permission problem for loading the script and icons, which I have not been able to understand yet. I'll continue investigating...

**Comment by wolfgangmm** [comment]
Version 1.1.1 should fix the problem.

**Comment by nathangibson** [comment]
@wolfgangmm Thanks so much for the prompt response!

**Comment by nathangibson** [comment]
@wolfgangmm FYI, this is working for me now :-)
